name: rbrmoored
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pytest
  - xarray
  - netcdf4
  - pip
  - isort
  - black
  - flake8
  - pdoc
  - pip:
    - pyrsktools
    - "-e ."
